### ISSUE TITLE
Need to decide what IDE we are using

### ISSUE THREAD

**Issue by UrOnMyHitList** [UrOnMyHitList/LetsGo#2]

**Comment by UrOnMyHitList** [comment]
I suggest Unity

**Comment by stefinnm** [comment]
I suggest sleeping

**Comment by paupypaup** [comment]
Android Studio?

**Comment by UrOnMyHitList** [comment]
Why Android Studio?

**Comment by stefinnm** [comment]
Android Studios

**Comment by flagninja** [comment]
Android studios sounds good.

**Comment by UrOnMyHitList** [comment]
Okay , we determined to use Android Studios since it has great development features and we can sync it to our github accounts.
